server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users?currentSchema=users
    username: postgres1
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: danieliusgrebliauskas@gmail.com
    password: suah wkaw dkth tltn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true